---
title: "Caribou DataViz"
author: "Julian Avila-Jimenez"
date: "2/8/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Caribou 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

#### Import the data
```{r import, message = FALSE, warning = FALSE}
library(tidyverse)
library(maps)
library(lubridate)
library(geosphere)
theme_set(theme_light())

caribou<- tidytuesdayR::tt_load("2020-06-23")
```

#### Individuals
```{r individuals, message = FALSE, warning = FALSE}
Ind<- caribou$individuals
Loc<- caribou$locations
Ind %>% summarize(across(sex:study_site,list(~mean(!is.na(.)))))

```

#### Explore the spatial information
```{r message = FALSE, warning = FALSE}
Ind %>% 
  count(study_site, 
        deploy_on_longitude,
        deploy_on_latitude,
        sort=T) %>% 
  ggplot(aes(deploy_on_longitude,
             deploy_on_latitude,
             size= n))+
  geom_point(color="deepskyblue4")
```
</br>
Here we have an outlayer below 30 degree latitude

```{r message = FALSE, warning = FALSE}
Ind %>% 
  filter(deploy_on_latitude>40) %>% 
  count(study_site, 
        deploy_on_longitude,
        deploy_on_latitude,
        sort=T) %>% 
  ggplot(aes(deploy_on_longitude,
             deploy_on_latitude,
             size= n,
             color= study_site))+
  geom_point(color="deepskyblue4")+
  labs(x="Longitude", 
       y="Latitude")+
  scale_size_continuous(guide=F)
```
</br>
much better! 


#### let's look to the Locations data
```{r}
Loc %>% 
  ggplot(aes(longitude,
             latitude,
             color= study_site))+
  geom_point()
```
</br>
A lot of points!!

### Animal movement over time

Let's take just one animal track and explore his seasonal movement

```{r}
ExampleAnimal<-Loc %>% 
  arrange(timestamp) %>% 
  filter(animal_id== sample(unique(animal_id),1))
 
ExampleAnimal %>% 
  mutate(quarter= as.Date(floor_date(timestamp, "quarter"))) %>% 
  ggplot(aes(longitude,
             latitude, 
             color= factor(floor_date(timestamp, "quarter"))))+
  geom_path()+
  labs(title = "Path of one caribou over time", 
       color="Quarter",
       caption = "Source: BC Ministry of Environment (2014)")+
  theme(legend.position="bottom")+
  facet_wrap(~ quarter)
```

### Total distance movement
```{r}
locations_time<- Loc %>% 
  group_by(animal_id) %>% 
  mutate(last_lat= lag(latitude),
         last_long= lag(longitude),
         hours= as.numeric(difftime(timestamp, 
                                    lag(timestamp),
                                    unit= "hours")),
         km= distHaversine(cbind(longitude, latitude),
                           cbind(last_long, last_lat))/1000,
         kph= km/ hours) %>% 
  ungroup()

locations_time %>% 
  filter(hours <=8,
         hours >=.5) %>% # just take the data with tracks between 0.5 and 8 hours
  ggplot(aes(kph))+
  geom_histogram(fill="deepskyblue4")+
  scale_x_log10(labels= scales::comma)+
  labs(title= "On average, how fast caribou travel?",
       caption = "Source: BC Ministry of Environment (2014)",
       y="",
       x="Km/h")
```

### Caribou average speed
```{r}
by_animal<-
  locations_time %>% 
  filter(hours <=8,
         hours >=.5) %>% # just take the data with tracks between 0.5 and 8 hours
  group_by(animal_id, study_site) %>% 
  summarise(start= min(timestamp),
            end= max(timestamp),
            num_points= n(),
            avg_speed= mean(kph[hours<=8], na.rm=T)) %>% 
  ungroup() %>% 
  arrange(desc(num_points)) %>% 
   filter(num_points>=10)

by_animal %>% 
  ggplot(aes(num_points, avg_speed))+
  geom_point(color="deepskyblue4")+
  scale_x_log10()+
  expand_limits(y=0)+
  labs(y = "Average speed",
       x= "Observations by Caribou",
       title = "Caribou Average Speed",
       caption = "Source: BC Ministry of Environment (2014)")
```


## Finaly the moveViz package!!
```{r moveViz, message = FALSE, warning = FALSE}
library(moveVis)
library(move)

data("move_data", package = "moveVis") # move class object
# if your tracks are present as data.frames, see df2move() for conversion
Loc2<- Loc %>% 
  filter(animal_id=="GR_C15") %>% 
  as.data.frame()

Locq<- df2move(Loc2, 
               proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0",
               x = "longitude", y = "latitude", 
               time = "timestamp", track_id = "animal_id")
# align move_data to a uniform time scale
m <- align_move(Locq, res = 1, unit = "days")

# create spatial frames with a OpenStreetMap watercolour map
frames <- frames_spatial(m, path_colours = c("red"),
                         map_service = "osm", 
                         map_type = "watercolor", 
                         alpha = 0.5) %>%
  add_labels(x = "Longitude", 
             y = "Latitude") %>% # add some customizations, such as axis labels
  add_northarrow() %>%
  add_scalebar() %>%
  add_timestamps(m, 
                 type = "label")

frames[[100]] # preview one of the frames, e.g. the 100th frame

# animate frames
animate_frames(frames, out_file = "moveVis.gif")
```

